services:

  DMP\RestBundle\Listener\SerializeListener:
    autowire: true
    tags:
      - { name: kernel.event_subscriber }

  DMP\RestBundle\Pagination\Listener\PaginationListener:
    autowire: true
    tags:
      - { name: kernel.event_subscriber }

  dmp_rest.serializer.symfony:
    autowire: true
    class: DMP\RestBundle\Serializer\SymfonySerializerAdapter
    public: false

  dmp_bundle.validation_exception_factory:
    class: DMP\RestBundle\Validation\ValidationExceptionFactory

  DMP\RestBundle\Listener\ExceptionListener:
    autowire: true
    arguments:
      $exceptionDTOFactory: '@DMP\RestBundle\Controller\DTO\ExceptionDTOFactory'
      $appEnv: '%env(APP_ENV)%'
    tags:
      - { name: kernel.event_subscriber }

  DMP\RestBundle\Controller\DTO\ExceptionDTOFactory: ~

  DMP\RestBundle\Pagination\Doctrine\QueryBuilderPaginator: ~

  DMP\RestBundle\Pagination\ArgumentResolver\PaginationArgumentValueResolver:
    arguments:
      $limit: '%dmp_rest.pagination.limit%'
      $maxLimit: '%dmp_rest.pagination.maxLimit%'
      $type: 'query'
    tags:
      - { name: controller.argument_value_resolver }
